apps/home/urls.py
from django.urls import path

from apps.home import views

app_name='home'
urlpatterns = [
    path('', views.index, name='index'),

]

apps/usuario/urls.py
from django.urls import path
from django.contrib import admin

from . import views

app_name='usuario'
urlpatterns = [
    path('login/', views.login_usuario, name='login'),
    path('editar/', views.editar_usuario, name='editar_usuario '),
    path('registrar/', views.registrar_usuario, name='registrar_usuario'),
    path('buscar-usuario/', views.buscar_usuario, name='buscar_usuario'),
]

sistUno/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('Deposito/', include('apps.deposito.urls')),
    path('Pago/', include('apps.pago.urls')),
    path('Solicitud/', include('apps.solicitud.urls')),
    path('Usuario/', include('apps.usuario.urls')),
    path('', include('apps.home.urls')),
]

apps/home/models.py
from django.db import models

# Create your models here.
class Banner(models.Model):
    titulo = models.CharField(max_length=100)
    banner = models.ImageField(blank=True, upload_to='banner')

    def __str__(self):
        return self.titulo

apps/home/views.py
from django.shortcuts import render, redirect

from apps.usuario.forms import NuevoUsuarioForm
from apps.home.models import Banner

def index(request):
    if request.method=='POST':
        form=NuevoUsuarioForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('home:index')
    else:
        form=NuevoUsuarioForm()

    banner = Banner.objects.all()

    return render(request, 'home/index.html',{'form':form,'banner':banner})

sistUno/templates/home/body.html
  <div class="panel panel-primary">
       <div class="panel-heading">Lorem ipsum dolor</div>
      <div class="panel-body">

        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

      </div>
    </div>

    <div class="panel panel-primary">
         <div class="panel-heading">Lorem ipsum dolor</div>
        <div class="panel-body">

          Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

        </div>
      </div>

sistUno/templates/home/index.html
{% extends 'base/base.html'%}
{% load staticfiles%}
{%block content%}
<div class="container">
  <div class="row">
    <!-- <div class="col-md-1">

    </div> -->
  <div class="col-md-9 box-body">
  {% include 'home/body.html'%}
  </div>
    <!-- LOGIN FORM -->
    <div class="col-md-3 box-login small">
      <h4>Ingresar</h4>
      <hr>
      <form class="" method="post">
        {% csrf_token %}

        <div class="form-group">
          <label for="id_correo">Correo electrónico</label>
          <input type="email" id="id_correo" name="email" placeholder="Correo electrónico" class="form-control">
        </div>
        <div class="form-group">
          <label for="id_contrasena">Contraseña</label>
          <input type="password" id="id_contrasena" name="email" placeholder="Contraseña" class="form-control">
        </div>

        <button type="submit" name="button" class="btn btn-primary btn-sm">Ingresar</button>
        <a href="{% url 'usuario:registrar_usuario'%}">¿No tienes una cuenta? Registrate</a>
      </form>
    </div>
    <!-- END LOGIN FORM -->
  </div>



  

{%endblock%}

sistUno/templates/home/slider.html
{% load staticfiles%}
<div class="slideshow">
  <ul class="slider">
    {% for ban in banner%}
    <li>
      <img src="{% static ''%}media/{{ban.banner}}" alt="">
      <section class="caption">

      </section>
    </li>
    {% endfor%}

  </ul>

  <!-- <ol class="pagination">

  </ol> -->



  <div class="left">
    <span class="fa fa-chevron-left"></span>
  </div>

  <div class="right">
    <span class="fa fa-chevron-right"></span>
  </div>

</div>

sistUno/templates/home/testimonios.html
{% load staticfiles%}
<div class="brand-logo-area">
  <div class="container">
    <div class="brand-logo">
      <div class="brand-logo-title">
        <h2>Testimonios</h2>
      </div>
      <div id="brands-logo" >
        <div class="testimonio-content text-center">
          <div class="testimonio-header">
            <div class="testimonio-photo">
              <img src="{% static 'img/fotos-usuario/7.jpg' %}" alt="" class="photo">
            </div>
          </div>
          <div class="testimonio-name">
            <h6>Usuario 1</h6>
          </div>
          <div class="testimonio-comment">
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
          </div>
          <div class="testimonio-date">
            <p>17-08-2018</p>
          </div>
        </div>

        <div class="testimonio-content text-center">
          <div class="testimonio-header">
            <div class="testimonio-photo">
              <img src="{% static 'img/fotos-usuario/2.jpg' %}" alt="" class="photo">
            </div>
          </div>
          <div class="testimonio-name">
            <h6>Usuario 2</h6>
          </div>
          <div class="testimonio-comment">
            <p>lorem Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
          </div>
          <div class="testimonio-date">
            <p>17-08-2018</p>
          </div>
        </div>

        <div class="testimonio-content text-center">
          <div class="testimonio-header">
            <div class="testimonio-photo">
              <img src="{% static 'img/fotos-usuario/3.jpg' %}" alt="" class="photo">
            </div>
          </div>
          <div class="testimonio-name">
            <h6>Usuario 3</h6>
          </div>
          <div class="testimonio-comment">
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
          </div>
          <div class="testimonio-date">
            <p>17-08-2018</p>
          </div>
        </div>

        <div class="testimonio-content text-center">
          <div class="testimonio-header">
            <div class="testimonio-photo">
              <img src="{% static 'img/fotos-usuario/4.jpg' %}" alt="" class="photo">
            </div>
          </div>
          <div class="testimonio-name">
            <h6>Usuario 4</h6>
          </div>
          <div class="testimonio-comment">
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
          </div>
          <div class="testimonio-date">
            <p>17-08-2018</p>
          </div>
        </div>
        <div class="testimonio-content text-center">
          <div class="testimonio-header">
            <div class="testimonio-photo">
              <img src="{% static 'img/fotos-usuario/5.jpg' %}" alt="" class="photo">
            </div>
          </div>
          <div class="testimonio-name">
            <h6>Usuario 5</h6>
          </div>
          <div class="testimonio-comment">
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
          </div>
          <div class="testimonio-date">
            <p>17-08-2018</p>
          </div>
        </div>
        <div class="testimonio-content text-center">
          <div class="testimonio-header">
            <div class="testimonio-photo">
              <img src="{% static 'img/fotos-usuario/6.jpg' %}" alt="" class="photo">
            </div>
          </div>
          <div class="testimonio-name">
            <h6>Usuario 6</h6>
          </div>
          <div class="testimonio-comment">
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
          </div>
          <div class="testimonio-date">
            <p>17-08-2018</p>
          </div>
        </div>


      </div>
    </div>
  </div>
</div>