apps/home/urls.py
from django.urls import path

from apps.home import views

app_name='home'
urlpatterns = [
    path('', views.index, name='index'),

]

apps/usuario/urls.py
from django.urls import path
from django.contrib import admin

from . import views

app_name='usuario'
urlpatterns = [
    path('login/', views.login_usuario, name='login'),
    path('editar/', views.editar_usuario, name='editar_usuario '),
    path('registrar/', views.registrar_usuario, name='registrar_usuario'),
    path('buscar-usuario/', views.buscar_usuario, name='buscar_usuario'),
]

sistUno/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('Deposito/', include('apps.deposito.urls')),
    path('Pago/', include('apps.pago.urls')),
    path('Solicitud/', include('apps.solicitud.urls')),
    path('Usuario/', include('apps.usuario.urls')),
    path('', include('apps.home.urls')),
]

apps/usuario/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator

# Create your models here.

class Entidad_bancaria(models.Model):
    nombre = models.CharField(max_length=50)
    logo = models.ImageField(blank=True, upload_to='entidades_bancarias')

    def __str__(self):
        return self.nombre


class Usuario(models.Model):
    dni = models.IntegerField(
        primary_key=True,
        validators=[MinValueValidator(10000000), 
        MaxValueValidator(99999999)],
        )
    nombres = models.CharField(max_length=50)
    apellido_paterno = models.CharField(max_length=50)
    apellido_materno = models.CharField(max_length=50)
    email = models.EmailField(max_length=60, unique=True)
    contraseña = models.CharField(max_length=100)
    foto_perfil = models.ImageField(blank=True, upload_to='usuario')
    numero_cuenta = models.IntegerField(unique=True)
    saldo = models.DecimalField(
        max_digits=10, decimal_places=2,
        blank=True, default=0
        )

        
    entidad_bancaria = models.ForeignKey(Entidad_bancaria, on_delete=models.PROTECT)
    dni_referido = models.ForeignKey('self', on_delete=models.PROTECT, blank=True, null=True)
    
    def __str__(self):
        return self.nombres

apps/usuario/forms.py
from django import forms
from django.core.files.images import ImageFile

from .models import Usuario

class NuevoUsuarioForm(forms.ModelForm):

    class Meta:
        model = Usuario

        fields = [
            'dni',
            'nombres',
            'apellido_paterno',
            'apellido_materno',
            'email',
            'foto_perfil',
            'dni_referido',
            'numero_cuenta',
            'entidad_bancaria',
            'contraseña',
        ]

        labels = {
            'dni': 'DNI',
            'nombres': 'Nombre(s)',
            'apellido_paterno': 'Apellido paterno',
            'apellido_materno': 'Apellido materno',
            'email': 'Dirección Correo electrónico',
            'foto_perfil': 'Foto de perfil',
            'dni_referido': 'DNI del referente',
            'numero_cuenta':'Numero de cuenta',
            'entidad_bancaria': 'Entidad bancaria',
            'contraseña': 'Contraseña',
        }

        widgets = {
            'dni': forms.NumberInput(attrs={'class': 'form-control-p'}),
            'nombres': forms.TextInput(attrs={'class': 'form-control-p'}),
            'apellido_paterno': forms.TextInput(attrs={'class': 'form-control-p'}),
            'apellido_materno': forms.TextInput(attrs={'class': 'form-control-p'}),
            'email': forms.EmailInput(attrs={'class': 'form-control-p'}),
            'foto_perfil': forms.FileInput(),
            'dni_referido': forms.NumberInput(attrs={'class': 'form-control-p'}),
            'numero_cuenta': forms.NumberInput(attrs={'class': 'form-control-p'}),
            'entidad_bancaria': forms.Select(attrs={'class': 'form-control-p'}),
            'contraseña': forms.TextInput(attrs={'class': 'form-control-p', 'type': 'password'}),
        }

apps/usuario/views.py
from django.shortcuts import render, redirect

from .forms import NuevoUsuarioForm
from .models import Usuario
from apps.home.models import Banner

# Create your views here.

def login_usuario(request):
    return render(request, 'usuario/login.html')

def editar_usuario(request):
    return render(request, 'usuario/editar.html')


def registrar_usuario(request):
    if request.method == 'POST':
        formUsuario = NuevoUsuarioForm(request.POST, request.FILES)
        if formUsuario.is_valid():
            formUsuario.save()
            return redirect('home:index')
    else:
        formUsuario = NuevoUsuarioForm()
    banner = Banner.objects.all()
    context = {
        'formUsuario': formUsuario,'banner':banner,
    }

    return render(request, 'usuario/registrar.html', context=context)


def buscar_usuario(request):
    if request.method == 'POST':
        if 'busqueda' in request.POST:
            busqueda = request.POST['busqueda']
        else:
            busqueda = ''
    else:
        busqueda = ''

    usuarios = Usuario.objects.filter(nombres__contains=busqueda)

    context = {
        'usuarios': usuarios
    }

    return render(request, 'usuario/buscar.html', context)

sistUno/templates/usuario/buscar.html
{% if usuarios.count > 0 %}

{% for usuario in usuarios %}
<div>
    <li>DNI del usuario de referencia: <a id="usuario-buscado-dni" href="#id_dni_referido">{{ usuario.dni }}</a></li>
    <li>Nombre(s): {{ usuario.nombres }}</li>
    <li>Apellido: {{ usuario.apellido_paterno }} {{ usuario.apellido_materno }}</li>
    <br>
</div>
{% endfor %}

{% else %}
    <li>No existe tal usuario</li>
{% endif %}

sistUno/templates/usuario/editar.html
<h1>Editar usuario</h1>

sistUno/templates/usuario/registrar.html
{% extends 'base/base.html' %} {% block header %} {% endblock %} {% block content %}
<div class="container">
    <div class="row">

      
        <div class="col-md-8 box-body">
          {% include 'home/body.html'%}
        </div>



        <div class="col-md-4 box-login small">
            <h4>Registrar Usuario</h4>
            <hr>
            <form enctype="multipart/form-data" method="POST" action="">

                {% csrf_token %} {{ formUsuario.as_p }}
                <button type="submit" class="btn btn-primary btn-sm">Guardar</button>
                <a href="{% url 'home:index' %}">Ya tengo una cuenta</a>
            </form>
            <hr>
            <h6>
                <b>Búsqueda de usuario referencia</b>
            </h6>

            <input type="text" id="busqueda" name="busqueda" class="form-control-p">



            <ul id="resultados-busqueda">

            </ul>
        </div>
    </div>

</div>

<!-- div col-md-4 -->



<script>
    $(function () {
        $('#busqueda').keyup(function () {
            var txt = $(this).val();
            if (txt === '') { }
            else {
                $.ajax({
                    type: "POST",
                    url: "/Usuario/buscar-usuario/",
                    data: {
                        'busqueda': $('#busqueda').val(),
                        'csrfmiddlewaretoken': $("input[name=csrfmiddlewaretoken]").val()
                    },
                    success: searchSuccess,
                    dataType: 'html'
                });
            }
        });
    });

    function searchSuccess(data, textStatus, jqXHR) {
        $('#resultados-busqueda').html(data);
    };


    var busq = document.getElementById("busqueda")
    busq.onchange = function() {selectorDNIreferido()};

    function selectorDNIreferido() {
        var dni = document.getElementById("usuario-buscado-dni");
        var dniFormField = document.getElementById("id_dni_referido");
        dniFormField.value = dni.text;
    };



</script>

{% endblock %}